version: '3.8'
services:
  mysql:
    container_name: mysql-con
    build: ./mysql 
    volumes:
      - data:/var/lib/mysql
    # image: wsjung0516/bookstore-mysql  
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
  server:
    container_name: server-con
    build: ./server 
    volumes:
       - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
       - mysql

  client:
    container_name: client-con
    build: ./client
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '80:80'
    depends_on:
       - server

volumes:
  data:

