###
GET http://ecs-lb-1894397438.us-east-1.elb.amazonaws.com/books
Content-Type: application/json

###
POST http://ecs-lb-1894397438.us-east-1.elb.amazonaws.com/books
Content-Type: application/json

{
        "title": "A Tale of Two Cities2",
        "description": "A story of two2",
        "author":  "John",
        "isActive": true
}
