###
GET http://52.91.4.4/books
Content-Type: application/json
###
GET http://23.20.37.236/books
Content-Type: application/json

###
POST http://localhost:3000/books
Content-Type: application/json

{
        "title": "A Tale of Two Cities2",
        "description": "A story of two2",
        "author":  "John",
        "isActive": true
}
