name: CI/CD counter app

on:
  push:
    branches: [ master ]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build the docker_compose
      run: docker-compose up -d --build
      
    # - name: Build the application
    #   run: docker-compose exec -T bookstore-nest npm run build

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOST_NAME }}
            USER_NAME : ${{ secrets.USER_NAME }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/runner/work/bookstore-nest220725/bookstore-nest220725 &&
            git checkout master &&
            git fetch --all &&
            git reset --hard origin/master &&
            git pull origin master &&
            docker-compose -f docker-compose.yml up -d --build 
          '